# Generated by Django 5.0.7 on 2024-08-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
