# Generated by Django 5.1 on 2024-08-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_descripcion_customuser_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='frase',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
