# Generated by Django 5.1 on 2024-08-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_frase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
