# Generated by Django 5.0.7 on 2024-07-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_remove_contenido_imagen_archivos_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagencategoria',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
