# Generated by Django 5.1 on 2024-08-18 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.CharField(blank=True, max_length=500, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True)),
                ('imagenetapa', models.ImageField(blank=True, null=True, upload_to='imgs')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='archivos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='contenidos.categoria'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='contenidos.categoria'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='etapa',
            field=models.ManyToManyField(blank=True, related_name='etapa', to='contenidos.etapa'),
        ),
        migrations.CreateModel(
            name='ArchivoMarcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_marcado', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.archivos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_marcados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'archivo')},
            },
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.TextField(blank=True, null=True)),
                ('fecha_problema', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_problema')},
            },
        ),
    ]
