# Generated by Django 5.1 on 2024-08-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_etapa_remove_archivos_contenido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Definicion1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicion1', models.TextField(blank=True, null=True)),
                ('fecha_definicion1', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definicion1_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_definicion1')},
            },
        ),
        migrations.CreateModel(
            name='Definicion2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicion2', models.TextField(blank=True, null=True)),
                ('fecha_definicion2', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definicion2_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_definicion2')},
            },
        ),
        migrations.CreateModel(
            name='Definicion3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicion3', models.TextField(blank=True, null=True)),
                ('fecha_definicion3', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definicion3_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_definicion3')},
            },
        ),
        migrations.CreateModel(
            name='Definicion4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicion4', models.TextField(blank=True, null=True)),
                ('fecha_definicion4', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definicion4_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_definicion4')},
            },
        ),
        migrations.CreateModel(
            name='Inclusivo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusivo1', models.TextField(blank=True, null=True)),
                ('fecha_inclusivo1', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivo1_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_inclusivo1')},
            },
        ),
        migrations.CreateModel(
            name='Inclusivo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusivo2', models.TextField(blank=True, null=True)),
                ('fecha_inclusivo2', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivo2_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_inclusivo2')},
            },
        ),
        migrations.CreateModel(
            name='Inclusivo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusivo3', models.TextField(blank=True, null=True)),
                ('fecha_inclusivo3', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivo3_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_inclusivo3')},
            },
        ),
        migrations.CreateModel(
            name='Inclusivo4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusivo4', models.TextField(blank=True, null=True)),
                ('fecha_inclusivo4', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivo4_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_inclusivo4')},
            },
        ),
        migrations.CreateModel(
            name='Inclusivo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusivo5', models.TextField(blank=True, null=True)),
                ('fecha_inclusivo5', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivo5_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_inclusivo5')},
            },
        ),
        migrations.CreateModel(
            name='Mapa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa1', models.TextField(blank=True, null=True)),
                ('fecha_mapa1', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapa1_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_mapa1')},
            },
        ),
        migrations.CreateModel(
            name='Mapa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa2', models.TextField(blank=True, null=True)),
                ('fecha_mapa2', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapa2_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_mapa2')},
            },
        ),
        migrations.CreateModel(
            name='Mapa3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa3', models.TextField(blank=True, null=True)),
                ('fecha_mapa3', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapa3_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_mapa3')},
            },
        ),
        migrations.CreateModel(
            name='Mapa4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa4', models.TextField(blank=True, null=True)),
                ('fecha_mapa4', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapa4_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_mapa4')},
            },
        ),
        migrations.CreateModel(
            name='Mapa5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapa5', models.TextField(blank=True, null=True)),
                ('fecha_mapa5', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapa5_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha_mapa5')},
            },
        ),
    ]
