# Generated by Django 5.1 on 2024-08-26 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0005_causas2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='causas2',
            options={'ordering': ['-fecha_causas2'], 'verbose_name': 'Etapa #2 - Identificación de causas', 'verbose_name_plural': 'Etapa #2 - Identificación de causas'},
        ),
        migrations.AlterModelOptions(
            name='definicion1',
            options={'ordering': ['-fecha_definicion1'], 'verbose_name': 'Etapa #1 - Definición inicial', 'verbose_name_plural': 'Etapa #1 - Definiciones iniciales'},
        ),
        migrations.CreateModel(
            name='Inclusivo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.TextField(blank=True, null=True)),
                ('dos', models.TextField(blank=True, null=True)),
                ('tres', models.TextField(blank=True, null=True)),
                ('cuatro', models.TextField(blank=True, null=True)),
                ('cinco', models.TextField(blank=True, null=True)),
                ('fecha_inclusivo2', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivo2_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa #2 - Enfoque inclusivo',
                'verbose_name_plural': 'Etapa #2 - Enfoque inclusivo',
                'ordering': ['-fecha_inclusivo2'],
                'unique_together': {('usuario', 'fecha_inclusivo2')},
            },
        ),
    ]
