# Generated by Django 5.1 on 2024-08-26 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0006_alter_causas2_options_alter_definicion1_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapadeafinidad2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.TextField(blank=True, null=True)),
                ('dos', models.TextField(blank=True, null=True)),
                ('tres', models.TextField(blank=True, null=True)),
                ('cuatro', models.TextField(blank=True, null=True)),
                ('cinco', models.TextField(blank=True, null=True)),
                ('fecha_mapadeafinidad2', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapadeafinidad2_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa #2 - Mapa de afinidad',
                'verbose_name_plural': 'Etapa #2 - Mapa de afinidad',
                'ordering': ['-fecha_mapadeafinidad2'],
                'unique_together': {('usuario', 'fecha_mapadeafinidad2')},
            },
        ),
    ]
