# Generated by Django 5.1 on 2024-08-28 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0007_mapadeafinidad2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusivo2',
            name='cinco',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='cuatro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='dos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='tres',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='uno',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Mapadeactores4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.TextField(blank=True, null=True)),
                ('dos', models.TextField(blank=True, null=True)),
                ('tres', models.TextField(blank=True, null=True)),
                ('cuatro', models.TextField(blank=True, null=True)),
                ('fecha_mapadeactores2', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapadeactores2_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa #2 - Mapa de actores',
                'verbose_name_plural': 'Etapa #2 - Mapa de actores',
                'ordering': ['-fecha_mapadeactores2'],
                'unique_together': {('usuario', 'fecha_mapadeactores2')},
            },
        ),
    ]
