# Generated by Django 5.1 on 2024-08-29 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0009_alter_mapadeactores4_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.TextField(blank=True, null=True)),
                ('dos', models.TextField(blank=True, null=True)),
                ('fecha_eventos4', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos4_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa #4 - Eventos',
                'verbose_name_plural': 'Etapa #4 - Eventos',
                'ordering': ['-fecha_eventos4'],
                'unique_together': {('usuario', 'fecha_eventos4')},
            },
        ),
    ]
