# Generated by Django 5.1 on 2024-10-19 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0011_film'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
