# Generated by Django 5.1 on 2024-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0012_delete_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='contenido',
        ),
        migrations.AlterUniqueTogether(
            name='problemas',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='problemas',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='definicion1',
            name='cuatro',
            field=models.TextField(blank=True, null=True, verbose_name='Dolor'),
        ),
        migrations.AlterField(
            model_name='definicion1',
            name='dos',
            field=models.TextField(blank=True, null=True, verbose_name='Dónde'),
        ),
        migrations.AlterField(
            model_name='definicion1',
            name='tres',
            field=models.TextField(blank=True, null=True, verbose_name='Cuándo'),
        ),
        migrations.AlterField(
            model_name='definicion1',
            name='uno',
            field=models.TextField(blank=True, null=True, verbose_name='Quién'),
        ),
        migrations.DeleteModel(
            name='ArchivoMarcado',
        ),
        migrations.DeleteModel(
            name='Archivos',
        ),
        migrations.DeleteModel(
            name='Etapa',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Problemas',
        ),
    ]
