# Generated by Django 5.1 on 2024-10-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0013_remove_archivos_categoria_remove_categoria_etapa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causas2',
            name='cinco',
        ),
        migrations.AlterField(
            model_name='causas2',
            name='cuatro',
            field=models.TextField(blank=True, null=True, verbose_name='Causa#4'),
        ),
        migrations.AlterField(
            model_name='causas2',
            name='dos',
            field=models.TextField(blank=True, null=True, verbose_name='Causa#2'),
        ),
        migrations.AlterField(
            model_name='causas2',
            name='tres',
            field=models.TextField(blank=True, null=True, verbose_name='Causa#3'),
        ),
        migrations.AlterField(
            model_name='causas2',
            name='uno',
            field=models.TextField(blank=True, null=True, verbose_name='Causa#1'),
        ),
    ]
