# Generated by Django 5.1 on 2024-12-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0014_remove_causas2_cinco_alter_causas2_cuatro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definicion1',
            options={'get_latest_by': 'fecha_definicion1', 'ordering': ['-fecha_definicion1'], 'verbose_name': 'Etapa #1 - Definición inicial', 'verbose_name_plural': 'Etapa #1 - Definiciones iniciales'},
        ),
        migrations.AlterField(
            model_name='eventos4',
            name='dos',
            field=models.TextField(blank=True, null=True, verbose_name='Acciones'),
        ),
        migrations.AlterField(
            model_name='eventos4',
            name='uno',
            field=models.TextField(blank=True, null=True, verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='cinco',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reflexión #5'),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='cuatro',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reflexión #4'),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='dos',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reflexión #2'),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='tres',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reflexión #3'),
        ),
        migrations.AlterField(
            model_name='inclusivo2',
            name='uno',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reflexión #1'),
        ),
        migrations.AlterField(
            model_name='mapadeafinidad2',
            name='cinco',
            field=models.TextField(blank=True, null=True, verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='mapadeafinidad2',
            name='cuatro',
            field=models.TextField(blank=True, null=True, verbose_name='Cuándo'),
        ),
        migrations.AlterField(
            model_name='mapadeafinidad2',
            name='dos',
            field=models.TextField(blank=True, null=True, verbose_name='Dónde'),
        ),
        migrations.AlterField(
            model_name='mapadeafinidad2',
            name='tres',
            field=models.TextField(blank=True, null=True, verbose_name='Dolor'),
        ),
        migrations.AlterField(
            model_name='mapadeafinidad2',
            name='uno',
            field=models.TextField(blank=True, null=True, verbose_name='Quién'),
        ),
        migrations.AlterField(
            model_name='oportunidades4',
            name='dos',
            field=models.TextField(blank=True, null=True, verbose_name='Amenazas'),
        ),
        migrations.AlterField(
            model_name='oportunidades4',
            name='uno',
            field=models.TextField(blank=True, null=True, verbose_name='Oportunidades'),
        ),
    ]
